[project]
name = "dns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "octodns-cloudflare>=1.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.9",
    "ty>=0.0.3",
]
